GET http://localhost:4000/review/

###

GET http://localhost:4000/review/5e93243a2c3d19237c0f6b20

###

POST http://localhost:4000/review/
Content-Type: application/json

{
    "service": "88",
    "message": "This is my message",
    "ratings": 3
}

###
DELETE http://localhost:4000/review/5e9325220407e812d4462b0c


### 

PATCH http://localhost:4000/review/5e93243a2c3d19237c0f6b20
Content-Type: application/json

{
    "ratings": "This is my patched experience"
}